.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.
.TH lunch 1 "JUL 2012" "LUNCH" "User Manuals"
.
.SH "NAME"
lunch \- calculate working hours from in\-out\-lunch
.
.SH "SYNOPSIS"
.
.B lunch
.RI [ file
\&...]
.
.SH "DESCRIPTION"
.
.B lunch
exists because I like to think of my working day as
\[lq]I arrived at 8.42, left at 18.32, and I had a 50-minute lunch\[rq],
yet every time reporting system I've used
wants me to report hours worked, to one or two decimal places.
.PP
So you feed
.B lunch
a text like this
.IP
.nf
.ft CR
# week of 2012-07-16
 8.45 16.36 0.50 # of which 3h environment fsckup
10.09 17.40 0.55
 9.07 21.13 0.50
 9.10 13.40 0.50 # dentist's appointment
 9.05 18.15 1.00
.fi
.PP
and it produces
.IP
.nf
.ft CR
# week of 2012-07-16
 8.45 16.36 0.50 -> 7h01m ( 7.02 h;  7.0 h) [-0.98]
10.09 17.40 0.55 -> 6h36m ( 6.60 h;  6.6 h) [-1.40]
 9.07 21.13 0.50 ->11h16m (11.27 h; 11.3 h) [+3.27]
 9.10 13.40 0.50 -> 3h40m ( 3.67 h;  3.7 h) [-4.33]
 9.05 18.15 1.00 -> 8h10m ( 8.17 h;  8.2 h) [+0.17]
.fi
.PP
In other words, lines starting with
.I in
.I out
.IR lunch ,
expressed as hours and minutes,
get calculated:
.IP \- 3x
working time in hours and minutes.
I chose the weird 8h10m format so you wouldn't accidentally
report this as your working time in decimal format.
.IP \-
working time in hours, rounded to two decimal places
.IP \-
working time in hours, rounded to one decimal place
.IP \-
delta from my standard working time, which is 8 hours.
Useful if your time reporting system forces you to
document this deviation manually.
.PP
I used to have another column where the hours were rounded
to nearest quarter of an hour, but fortunately I no longer
need to use the time reporting system which wanted that
weird variation.
.
.
.SH "BUGS"
You may not like the data formats used (e.g.
.IR hours . minutes
is swedish standard syntax;
.IR hours . decimals
is scientific syntax).
I won't fix that \- but you're free to fork from
.IR \[fo]https://github.com/kjgrahn/lunch\[fc] .
.
.
.SH "AUTHOR"
.
J\(:orgen Grahn
.IR \[fo]grahn+src@snipabacken.se\[fc] .
.
.
.SH "LICENSE"
.
The Modified BSD license.
